### PR TITLE
[solution]: zh/medium-camelcase

### PR DESCRIPTION
**Pull request by likui628**
# Challenge [zh/medium-camelcase]

## Checklist

- [x] Make sure that you are opening the PR with a single solution (one solution per PR)
- [x] The solution must have at least several references for the readers to dive in depth

### CODE REVIEW

**Review by charleserious — CHANGES_REQUESTED** [review]
Do we agree on this?

**Comment by likui628** [comment]
> Do we agree on this?

much better

> Do we agree on this?

much better

**Comment by likui628** [comment]
> Do we agree on this?

much better

**Review by charleserious — APPROVED** [review]
LGTM

**Pull request merged**
