### PR TITLE
[chore]: settle a place for convertions used in Chinese translation

### PR DESCRIPTION
**Pull request by charleserious**
In order to make some agreements in Chinese translation, we need settle a place for conventions, this `README` is a way we discussed in [a issue comment](https://github.com/ghaiklor/type-challenges-solutions/issues/147#issuecomment-1037174844), the reason naming the file to `README.md` is that we could use the [README Feature](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes) offered by Github.

### CODE REVIEW

**Comment by ghaiklor** [comment]
@charleserious the `??` folders are meant to be the source code for the views. Anything that goes there must be present on website. Let's move it to the root of the project, as I mentioned in the issue. I'll update the PR to show you what I mean.

**Comment by ghaiklor** [comment]
To be the "glossary" in its term there is an absent meaning for the term, to be more precise. Maybe you could add a few words about the meaning of the word to explain others why this exact term was chosen.

**Comment by charleserious** [comment]
> @charleserious the `??` folders are meant to be the source code for the views. Anything that goes there must be present on website. Let's move it to the root of the project, as I mentioned in the issue. I'll update the PR to show you what I mean.

Sorry for the misunderstanding, and thank you for the correction. 👍

**Comment by charleserious** [comment]
> To be the "glossary" in its term there is an absent meaning for the term, to be more precise. Maybe you could add a few words about the meaning of the word to explain others why this exact term was chosen.

Ha, you make the point, and I'll clarify the meaning for the chosen ones.

**Review by likui628 — APPROVED** [review]

**Review by ghaiklor — CHANGES_REQUESTED** [review]
There is a meaning missing and still an ongoing discussion about the glossary as a file

**Review by charleserious — COMMENTED** [review]
@likui628 can you help me on these three `Variadic Tuple Types`, `Conditional Types`, `Flat Type`? I don't have any idea on how to express these in Chinese.

**Comment by charleserious** [comment]
@likui628 I'v tweaked a little, PTAL

**Review by likui628 — DISMISSED** [review]

**Comment by charleserious** [comment]
> There is a meaning missing and still an ongoing discussion about the glossary as a file

@ghaiklor I think we're good to go~

**Comment by ghaiklor** [comment]
@charleserious what about making it a list? It looks great in the table, but the source code is hard to read. Let's make it just a list. e.g

```markdown
- <ENGLISH TERM> (<CHINESE TERM>) - <MEANING>
```

What do you think?

**Comment by charleserious** [comment]
@ghaiklor Can not come up with more appropriate one, your suggestion looks great. 
Thx.

**Comment by charleserious** [comment]
@ghaiklor hey bro, are you ok? Hope you well through this war. ☮️🙏🇺🇦

**Comment by ghaiklor** [comment]
@charleserious hey, still alive, thanks! Our army stands firm against the genocide from Russian occupants.

**Comment by charleserious** [comment]
@ghaiklor send Russians home~

**Review by ghaiklor — APPROVED** [review]

**Comment by ghaiklor** [comment]
@charleserious I'm not fully available, but I can have some spare time on a occasion. So feel free to contribute and thanks for this!

**Comment by charleserious** [comment]
@ghaiklor Hope your family going well, I recently focus on my daily job, but I'll keep contributing when I'm free to.

**Pull request merged**
