### PR TITLE
Partial Ukrainian localisation

### PR DESCRIPTION
**Pull request by bdvorianov**
Created directory `uk/` with duplicates from `en/` to make diffs at PR's and added translated versions of a few of challenges.

### CODE REVIEW

**Comment by ghaiklor** [comment]
It would be great to have separate commits for each challenge. You can continue working here and I'll just cherry-pick what needed into main branch. Or, if you want, I can tell more about cherry-pick so you can do it yourself.

It will be hard to trace the translation if we will merge all the translations into one commit from here 😢

**Comment by ghaiklor** [comment]
Also, you have a linter violation https://travis-ci.com/github/ghaiklor/type-challenges-solutions/builds/222097440#L381

**Comment by ghaiklor** [comment]
BTW, you have a push access to main branch, so you can just commit directly into main branch when a challenge is translated.

**Comment by bdvorianov** [comment]
Agree. It may be faster and easier just to commit the changes one by one, not cherry-picking.

Can you please help me with the linter error? It seems like smth wrong with expressions like `{{ }}`, but I'm not familiar enough to fix it with just one commit. Btw, there's error on `en` and, probably `ru` indexes, see the bottom of files.

**Comment by ghaiklor** [comment]
@bdvorianov you can ignore those. The build is failing because

```
find . -name '*.md' ! -path './vendor/*' | xargs bundle exec mdl
381./uk/easy-if.md:12: MD009 Trailing spaces
382./uk/easy-includes.md:21: MD012 Multiple consecutive blank lines
383./uk/easy-includes.md:30: MD012 Multiple consecutive blank lines
```

**Comment by ghaiklor** [comment]
Running `make lint` or better `make all` would run everything on your machine as it runs on CI.

**Comment by bdvorianov** [comment]
Thanks!

I'm trying to install `make` and, before it, to update `xcode` configuration as well at parallel, but it's kinda messed.

**Comment by ghaiklor** [comment]
I just read through the translation and it felt like you were translating from Russian to Ukrainian, do you? 😿

**Comment by bdvorianov** [comment]
I'm going through `en` version sentence by sentence, replacing the original with the Ukrainian equivalent. Sometimes checking with `ru` version to make sure it will be complete and have the same idea. Not sure, but @rosyurch said he has similar flow.

**Comment by bdvorianov** [comment]
BTW, how am I supposed to name commit adding `uk` with files copied from `en`?

I need it to have diffs like this https://github.com/bdvorianov/type-challenges-solutions/pull/2/files, so it will be more convenient to track the changes.

**Comment by bdvorianov** [comment]
Moved to: https://github.com/ghaiklor/type-challenges-solutions/pull/21

**Comment by rosyurch** [comment]
> 
> 
> I'm going through `en` version sentence by sentence, replacing the original with the Ukrainian equivalent. Sometimes checking with `ru` version to make sure it will be complete and have the same idea. Not sure, but @rosyurch said he has similar flow. @rosyurch, do you? 👀

that's the case, indeed

**Pull request closed without merging**
